# Site settings
title: Wil Maltby
description: Hey all, this is where I share things I'm building and some excerpts from books I'm reading.
logo: /assets/img/logo.png  # Add your logo image here (optional)
show_downloads: false  # Set to true if you want to show download buttons for your projects

# Theme setting
theme: jekyll-theme-minimal

# Social links (optional)
github_username: wil-maltby
